import React, { useRef } from 'react';
import { ComicStory } from '../types';
import { Trash2, Download, Share2 } from 'lucide-react';

interface ComicStripProps {
  story: ComicStory;
  onRemove: (id: string) => void;
}

export const ComicStrip: React.FC<ComicStripProps> = ({ story, onRemove }) => {
  const stripRef = useRef<HTMLDivElement>(null);

  const handleDownload = () => {
    alert("To save the comic, please long-press or right click the image!");
  };

  const isStripLayout = story.layout === 'strip' || story.panels.length === 1;

  return (
    <div className="w-full max-w-lg mx-auto mb-16 animate-in fade-in slide-in-from-bottom-4 duration-700">
      
      {/* Strip Header */}
      <div className="bg-white p-4 rounded-t-xl border-x-4 border-t-4 border-chiikawa-dark flex justify-between items-start">
        <div>
          <h3 className="font-serif text-xl font-bold text-chiikawa-dark line-clamp-1">
             {story.prompt}
          </h3>
          <p className="text-xs text-gray-400 mt-1">
             {new Date(story.timestamp).toLocaleDateString()} • {story.characters.join(', ')}
          </p>
        </div>
        <div className="flex gap-2">
          <button onClick={() => onRemove(story.id)} className="text-gray-300 hover:text-red-400 transition-colors">
            <Trash2 size={18} />
          </button>
        </div>
      </div>

      {/* Comic Content */}
      <div ref={stripRef} className="border-x-4 border-b-4 border-chiikawa-dark bg-white shadow-2xl overflow-hidden">
        {isStripLayout ? (
           /* SINGLE IMAGE STRIP MODE */
           <div className="w-full relative group">
             <img 
               src={story.panels[0].imageUrl} 
               alt="Generated Chiikawa Comic Strip"
               className="w-full h-auto block"
             />
             {/* Hover overlay for download hint */}
             <div className="absolute inset-0 bg-black/0 group-hover:bg-black/5 transition-colors flex items-center justify-center pointer-events-none">
             </div>
           </div>
        ) : (
           /* LEGACY GRID MODE (4 separate images) */
           <div className="flex flex-col">
             {story.panels.map((panel, index) => (
               <div key={index} className="relative w-full aspect-square border-b-4 border-chiikawa-dark last:border-b-0 group">
                 <img 
                   src={panel.imageUrl} 
                   alt={`Panel ${panel.panelNumber}`}
                   className="w-full h-full object-cover"
                 />
                 <div className="absolute top-2 left-2 bg-black/10 text-black/50 font-bold px-2 py-1 text-xs rounded-full backdrop-blur-sm opacity-0 group-hover:opacity-100 transition-opacity">
                   {index + 1}
                 </div>
                 <div className="absolute bottom-0 left-0 right-0 bg-black/70 text-white text-[10px] p-2 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none">
                   <span className="font-bold text-yellow-300">Dialogue:</span> {panel.dialogue || "(Silent)"}
                 </div>
               </div>
             ))}
           </div>
        )}
      </div>

      {/* Footer / Branding */}
      <div className="mt-4 flex justify-center">
         <div className="text-chiikawa-text/40 text-xs font-serif italic flex items-center gap-1">
            Generated by Chiikawa Maker 
            {isStripLayout && <span className="bg-chiikawa-pink/20 text-chiikawa-pink px-1.5 py-0.5 rounded text-[10px] font-bold">V2</span>}
         </div>
      </div>
    </div>
  );
};